
library(duckdb)
library(DBI)
library(dplyr)
source(here::here("R", "create_all_tables.R"))

# Specify the path where the raw .csv files from are stored
csv_dir <- here::here("data", "rawdat", "state")

# Specify the path to .duckdb file for database
database_path <-
  here::here("data", "db", "foresttime-to-share.duckdb")

if (file.exists(database_path)) {
  file.remove(database_path)
}

# Connect to database
con <- dbConnect(duckdb(dbdir = database_path))

rawdat_dir <- csv_dir


tree_query <- paste0(
  "CREATE TABLE tree AS SELECT CN AS TREE_CN, PLT_CN, PREV_TRE_CN, INVYR, STATECD, UNITCD, COUNTYCD, PLOT, SUBP, TREE, CONDID, AZIMUTH, DIST, PREVCOND, STATUSCD, SPCD, SPGRPCD, DIA, DIAHTCD, HT, HTCD, ACTUALHT, TREECLCD, CR, CCLCD, TREEGRCD, AGENTCD, CULL, DAMLOC1, DAMTYP1, DAMSEV1, DAMLOC2, DAMTYP2, DAMSEV2, DECAYCD, STOCKING, WDLDSTEM, VOLCFNET, VOLCFGRS, VOLCSNET, VOLCSGRS, VOLBFNET, VOLBFGRS, VOLCFSND, DIACHECK, MORTYR, SALVCD, UNCRCD, CPOSCD, CLIGHTCD, CVIGORCD, CDENCD, CDIEBKCD, TRANSCD, TREEHISTCD, BHAGE, TOTAGE, CULLDEAD, CULLFORM, CULLMSTOP, CULLBF, CULLCF, BFSND, CFSND, SAWHT, BOLEHT, FORMCL, HTCALC, HRDWD_CLUMP_CD, SITREE, MORTCD, HTDMP, ROUGHCULL, MIST_CL_CD, CULL_FLD, RECONCILECD, PREVDIA, P2A_GRM_FLG, TREECLCD_NERS, TREECLCD_SRS, TREECLCD_NCRS, TREECLCD_RMRS, STANDING_DEAD_CD, PREV_STATUS_CD, PREV_WDLDSTEM, TPA_UNADJ, DRYBIO_BOLE, DRYBIO_STUMP, DRYBIO_BG, CARBON_AG, CARBON_BG, CYCLE, SUBCYCLE, BORED_CD_PNWRS, DAMLOC1_PNWRS, DAMLOC2_PNWRS, DIACHECK_PNWRS, DMG_AGENT1_CD_PNWRS, DMG_AGENT2_CD_PNWRS, DMG_AGENT3_CD_PNWRS, MIST_CL_CD_PNWRS, SEVERITY1_CD_PNWRS, SEVERITY1A_CD_PNWRS, SEVERITY1B_CD_PNWRS, SEVERITY2_CD_PNWRS, SEVERITY2A_CD_PNWRS, SEVERITY2B_CD_PNWRS, SEVERITY3_CD_PNWRS, UNKNOWN_DAMTYP1_PNWRS, UNKNOWN_DAMTYP2_PNWRS, PREV_PNTN_SRS, DISEASE_SRS, DIEBACK_SEVERITY_SRS, DAMAGE_AGENT_CD1, DAMAGE_AGENT_CD2, DAMAGE_AGENT_CD3, CENTROID_DIA, CENTROID_DIA_HT, CENTROID_DIA_HT_ACTUAL, UPPER_DIA, UPPER_DIA_HT, VOLCSSND, DRYBIO_SAWLOG, DAMAGE_AGENT_CD1_SRS, DAMAGE_AGENT_CD2_SRS, DAMAGE_AGENT_CD3_SRS, DRYBIO_AG, ACTUALHT_CALC, ACTUALHT_CALC_CD, CULL_BF_ROTTEN, CULL_BF_ROTTEN_CD, CULL_BF_ROUGH, CULL_BF_ROUGH_CD, PREVDIA_FLD, TREECLCD_31_NCRS, TREE_GRADE_NCRS, BOUGHS_AVAILABLE_NCRS, BOUGHS_HRVST_NCRS, TREECLCD_31_NERS, AGENTCD_NERS, BFSNDCD_NERS, AGECHKCD_RMRS, PREV_ACTUALHT_RMRS, PREV_AGECHKCD_RMRS, PREV_BHAGE_RMRS, PREV_HT_RMRS, PREV_TOTAGE_RMRS, PREV_TREECLCD_RMRS, RADAGECD_RMRS, RADGRW_RMRS, VOLBSGRS, VOLBSNET, SAPLING_FUSIFORM_SRS, EPIPHYTE_PNWRS, ROOT_HT_PNWRS, CAVITY_USE_PNWRS, CORE_LENGTH_PNWRS, CULTURALLY_KILLED_PNWRS, DIA_EST_PNWRS, GST_PNWRS, INC10YR_PNWRS, INC5YRHT_PNWRS, INC5YR_PNWRS, RING_COUNT_INNER_2INCHES_PNWRS, RING_COUNT_PNWRS, SNAG_DIS_CD_PNWRS, CONEPRESCD1, CONEPRESCD2, CONEPRESCD3, MASTCD, VOLTSGRS, VOLTSGRS_BARK, VOLTSSND, VOLTSSND_BARK, VOLCFGRS_STUMP, VOLCFGRS_STUMP_BARK, VOLCFSND_STUMP, VOLCFSND_STUMP_BARK, VOLCFGRS_BARK, VOLCFGRS_TOP, VOLCFGRS_TOP_BARK,  VOLCFSND_BARK,  VOLCFSND_TOP,  VOLCFSND_TOP_BARK,  VOLCFNET_BARK,  VOLCSGRS_BARK,  VOLCSSND_BARK,  VOLCSNET_BARK,  DRYBIO_STEM,  DRYBIO_STEM_BARK,  DRYBIO_STUMP_BARK,  DRYBIO_BOLE_BARK,  DRYBIO_BRANCH,  DRYBIO_FOLIAGE, DRYBIO_SAWLOG_BARK, CONCAT_WS('_', STATECD, UNITCD, COUNTYCD, PLOT, SUBP, TREE) AS TREE_COMPOSITE_ID, CONCAT_WS('_', STATECD, UNITCD, COUNTYCD, PLOT) AS PLOT_COMPOSITE_ID FROM '",
  csv_dir,
  "/*_TREE.csv' WHERE (INVYR >= 2000.0)"
)

dbExecute(con, tree_query)

dbDisconnect(con, shutdown = T)

file.remove(database_path)
