on:
  push:
    branches: v-paralell

jobs:
  bifurcated-1:
    runs-on: ubuntu-latest
    env:
      BOX_TOKEN_TEXT: ${{ secrets.BOX_TOKEN_TEXT }}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyr
            any::duckdb
            any::arrow
            any::here
            any::DBI
            any::stringr
            any::purrr
            any::dbplyr
            any::boxr
            any::jose
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up directories
        run: Rscript -e 'source("scripts/A-state-parquet.R")'
